import { day, dayAt, minutesAgo, yesterdayAt } from "../../../lib/sampleTime";
import type { StudentChatThread, StudentWork } from "../types";

/*
 * 내 작업 임시 예시 데이터 (피그마 「작업 진행 · 수정 요청 확인 · 수정안 제출 · 제출한 초안 보기 ·
 * 내 결과물 보기 · 받은 후기 보기 · 작업 시작 · 취소된 작업 · 채팅방」 내용).
 * 홈 · 내 활동 · 정산 내역 · 내 작업물 · 채팅 목록은 이 데이터에서 만든다. 날짜는 오늘 기준.
 * work-103 · work-090 은 사장님 예시(features/owner/lib/sampleDetails.ts)의 같은 작업이라
 * 금액 · 날짜 · 작업계획서 · 채팅이 같다.
 */

export const SAMPLE_WORKS: StudentWork[] = [
  {
    id: "work-103",
    kind: "request",
    title: "메뉴판 디자인 변경",
    field: "디자인",
    tasks: ["메뉴판·가격표 디자인"],
    store: { id: "store-chicken", name: "치킨플러스" },
    budget: 60000,
    draftDue: day(7),
    finalDue: day(10),
    revisionLimit: 1,
    revisionCount: 0,
    plan: "초록색을 살린 메뉴판 시안 2가지를 만들고, 고르신 쪽으로 다듬어 인쇄용으로 드릴게요.\n· 방법: 보내 주신 메뉴 사진을 보정해서 넣고, 인기 메뉴 3개는 크게 보여 드려요.\n· 일정: 초안 마감일까지 초안 2가지, 수정 요청이 오면 최종 마감일까지 최종본을 드려요.",
    planSentOn: day(-4),
    status: "drafting",
    startedOn: day(-2),
    files: [],
    history: [
      { date: day(-4), text: "지원" },
      { date: day(-2), text: "의뢰 선정 · 작업 시작" },
    ],
  },
  {
    id: "work-211",
    kind: "request",
    title: "인스타 게시물 5개 제작",
    field: "홍보",
    tasks: ["SNS 게시물"],
    store: { id: "store-kwcafe", name: "광운카페" },
    budget: 40000,
    draftDue: day(-4),
    finalDue: day(2),
    revisionLimit: 1,
    revisionCount: 1,
    plan: "시험 기간 이벤트와 신메뉴를 알리는 인스타 게시물 5장을 만들어 드릴게요.\n· 방법: 매장 사진을 밝게 보정하고, 게시물마다 한 줄 문구를 크게 넣어요.\n· 일정: 초안 마감일까지 초안 5장, 수정 요청이 오면 최종 마감일까지 최종본을 드려요.",
    planSentOn: day(-11),
    status: "revising",
    startedOn: day(-9),
    files: [
      { name: "인스타_게시물_5장.zip", size: "16.4MB" },
      { name: "게시물_문구.txt", size: "4KB" },
    ],
    myMessage: "게시물 5장과 올릴 때 쓸 문구를 함께 보내 드려요.",
    submittedOn: day(-4),
    revisionRequest: {
      requestedOn: day(-1),
      text: "2번 게시물 사진을 조금 더 밝게 해 주세요. 4번 게시물에는 시험 기간 이벤트 문구를 넣어 주세요.",
      attachments: ["밝기_참고.jpg"],
    },
    history: [
      { date: day(-9), text: "의뢰 선정 · 작업 시작" },
      { date: day(-4), text: "초안 제출 (게시물 5장)" },
      { date: day(-1), text: "수정 요청 · 사진 밝기, 이벤트 문구" },
    ],
  },
  {
    id: "work-212",
    kind: "proposal",
    proposalId: "prop-305",
    title: "카카오 맵 영업시간 수정",
    field: "홍보",
    tasks: ["SNS 게시물"],
    store: { id: "store-bunsik", name: "월계분식" },
    budget: 30000,
    draftDue: day(-1),
    finalDue: day(4),
    revisionLimit: 1,
    revisionCount: 0,
    plan: "카카오 맵의 영업시간 · 휴무일 · 대표 사진을 지금 가게와 똑같이 고쳐 드릴게요.\n· 방법: 가게 안내문과 하나씩 대조해서 틀린 곳을 고치고, 대표 사진 3장을 새로 찍어 올려요.\n· 일정: 초안 마감일까지 고칠 목록과 사진을 보내 드리고, 확인해 주시면 바로 반영해요.",
    planSentOn: day(-9),
    status: "submitted",
    requestArrivedOn: day(-7),
    startedOn: day(-6),
    files: [
      { name: "카카오맵_수정_목록.pdf", size: "1.2MB" },
      { name: "대표사진_3장.zip", size: "9.6MB" },
    ],
    myMessage: "영업시간과 일요일 휴무를 고칠 목록, 새로 찍은 대표 사진 3장을 보내 드려요.",
    submittedOn: day(-1),
    autoCompleteOn: day(6),
    history: [
      { date: day(-9), text: "제안 보냄" },
      { date: day(-7), text: "제안 수락 · 의뢰서 도착" },
      { date: day(-6), text: "조건 동의 · 작업 시작" },
      { date: day(-1), text: "초안 제출 (수정 목록 · 사진 3장)" },
    ],
  },
  {
    id: "work-213",
    kind: "proposal",
    proposalId: "prop-303",
    title: "외국어 메뉴판 만들기",
    field: "글쓰기·번역",
    tasks: ["메뉴판·가격표 디자인", "영어 번역"],
    store: { id: "store-bunsik", name: "월계분식" },
    budget: 50000,
    draftDue: day(4),
    finalDue: day(7),
    revisionLimit: 1,
    revisionCount: 0,
    plan: "· 방법: 메뉴 이름은 소리 나는 대로 적고, 재료와 맛을 한 줄로 설명해요.\n· 일정: 초안 2일, 수정 뒤 최종본까지 4일 걸려요.\n· 결과물: 사진을 넣은 인쇄용 메뉴판 PDF",
    planSentOn: day(-5),
    status: "awaitingAgreement",
    requestArrivedOn: day(0),
    ownerMessage: "오후 3~5시는 한가해요. 그때 가게에 오시면 메뉴 하나하나 설명해 드릴게요!",
    files: [],
    history: [
      { date: day(-5), text: "제안 보냄" },
      { date: day(0), text: "제안 수락 · 의뢰서 도착" },
    ],
  },
  {
    id: "work-090",
    kind: "request",
    title: "메뉴판 제작",
    field: "디자인",
    tasks: ["메뉴판·가격표 디자인"],
    store: { id: "store-chicken", name: "치킨플러스" },
    budget: 50000,
    draftDue: day(-14),
    finalDue: day(-10),
    revisionLimit: 1,
    revisionCount: 1,
    plan: "지금 메뉴를 한눈에 보이게 정리한 A3 메뉴판을 만들어 드릴게요.",
    planSentOn: day(-21),
    status: "completed",
    startedOn: day(-17),
    completedOn: day(-10),
    completedBy: "owner",
    files: [
      { name: "메뉴판_최종.pdf", size: "8.4MB" },
      { name: "메뉴판_원본.ai", size: "32.0MB" },
    ],
    myMessage: "가격을 고친 최종본이에요. 인쇄소에 PDF를 그대로 보내시면 돼요!",
    resultSummary: "A3 메뉴판 · 수정 1회 반영",
    history: [
      { date: day(-17), text: "의뢰 선정 · 작업 시작" },
      { date: day(-14), text: "초안 제출 (메뉴판 시안 2가지)" },
      { date: day(-13), text: "수정 요청 · 가격, 글자 크기" },
      { date: day(-10), text: "수정안 제출 · 사장님이 완료 확인" },
    ],
  },
  {
    id: "work-201",
    kind: "request",
    title: "가게 로고 디자인",
    field: "디자인",
    tasks: ["로고 디자인"],
    store: { id: "store-dino", name: "공룡카페" },
    budget: 70000,
    draftDue: day(-25),
    finalDue: day(-21),
    revisionLimit: 1,
    revisionCount: 1,
    plan: "공룡 캐릭터를 넣은 로고 시안 4가지를 만들고, 고르신 쪽을 간판 · 스티커용으로 다듬어 드릴게요.",
    planSentOn: day(-30),
    status: "completed",
    startedOn: day(-28),
    completedOn: day(-21),
    completedBy: "owner",
    files: [
      { name: "공룡카페_로고_최종.zip", size: "12.4MB" },
      { name: "공룡카페_로고_원본.ai", size: "8.2MB" },
    ],
    myMessage: "말씀하신 색 조합으로 바꾼 최종본이에요. 스티커용 파일도 함께 넣었어요.",
    resultSummary: "로고 시안 4장 · 수정 1회 반영",
    review: {
      rating: 5,
      points: ["결과물이 좋아요", "마감을 잘 지켜요", "친절해요"],
      text: "귀여운 공룡 캐릭터가 가게랑 잘 어울려요. 스티커로도 만들어 쓰고 있어요!",
      date: day(-21),
    },
    history: [
      { date: day(-28), text: "의뢰 선정 · 작업 시작" },
      { date: day(-25), text: "초안 제출 (시안 4장)" },
      { date: day(-24), text: "수정 요청 · 색 조합" },
      { date: day(-21), text: "수정안 제출 · 사장님이 완료 확인" },
    ],
  },
  {
    id: "work-202",
    kind: "request",
    title: "단골 도장카드 디자인",
    field: "디자인",
    tasks: ["쿠폰·스티커·명함 디자인"],
    store: { id: "store-dino", name: "공룡카페" },
    budget: 50000,
    draftDue: day(-28),
    finalDue: day(-25),
    revisionLimit: 1,
    revisionCount: 0,
    plan: "도장 10개를 모으면 음료 한 잔을 주는 명함 크기 도장카드를 만들어 드릴게요.",
    planSentOn: day(-33),
    status: "completed",
    startedOn: day(-31),
    completedOn: day(-25),
    completedBy: "owner",
    files: [{ name: "도장카드_최종.pdf", size: "3.2MB" }],
    myMessage: "앞면에는 공룡 캐릭터, 뒷면에는 도장 칸 10개를 넣었어요.",
    resultSummary: "도장카드 앞뒤 2면",
    history: [
      { date: day(-31), text: "의뢰 선정 · 작업 시작" },
      { date: day(-28), text: "초안 제출 (앞뒤 2면)" },
      { date: day(-25), text: "사장님이 완료 확인" },
    ],
  },
  {
    id: "work-203",
    kind: "request",
    title: "리뷰 분석 리포트",
    field: "분석",
    tasks: ["리뷰 분석"],
    store: { id: "store-kwcafe", name: "광운카페" },
    budget: 30000,
    draftDue: day(-35),
    finalDue: day(-30),
    revisionLimit: 1,
    revisionCount: 0,
    plan: "최근 리뷰 100개를 읽고 손님이 좋아하는 점과 아쉬운 점을 한 장으로 정리해 드릴게요.",
    planSentOn: day(-40),
    status: "completed",
    startedOn: day(-38),
    completedOn: day(-28),
    completedBy: "auto",
    files: [{ name: "리뷰분석_리포트.pdf", size: "1.4MB" }],
    myMessage: "좋아하는 점 3가지, 아쉬운 점 3가지와 바로 해 볼 수 있는 일을 정리했어요.",
    resultSummary: "리포트 1장",
    history: [
      { date: day(-38), text: "의뢰 선정 · 작업 시작" },
      { date: day(-35), text: "초안 제출 (리포트 1장)" },
      { date: day(-28), text: "7일 지나 자동 완료" },
    ],
  },
  {
    id: "work-204",
    kind: "request",
    title: "배달앱 메뉴 설명 글",
    field: "글쓰기·번역",
    tasks: ["소개·공지 글쓰기"],
    store: { id: "store-bunsik", name: "월계분식" },
    budget: 30000,
    draftDue: day(-40),
    finalDue: day(-36),
    revisionLimit: 1,
    revisionCount: 0,
    plan: "배달앱 메뉴 20개에 맛이 느껴지는 짧은 설명을 달아 드릴게요.",
    planSentOn: day(-45),
    status: "completed",
    startedOn: day(-43),
    completedOn: day(-36),
    completedBy: "owner",
    files: [{ name: "배달앱_메뉴설명.docx", size: "48KB" }],
    myMessage: "메뉴마다 두 줄 안으로 맛과 양을 적었어요.",
    resultSummary: "메뉴 설명 20개",
    review: {
      rating: 4,
      points: ["결과물이 좋아요", "친절해요"],
      text: "메뉴마다 맛이 잘 느껴지게 써 줬어요. 배달 주문이 늘었어요.",
      date: day(-36),
    },
    history: [
      { date: day(-43), text: "의뢰 선정 · 작업 시작" },
      { date: day(-40), text: "초안 제출 (메뉴 설명 20개)" },
      { date: day(-36), text: "사장님이 완료 확인" },
    ],
  },
  {
    id: "work-205",
    kind: "proposal",
    proposalId: "prop-302",
    title: "시험 기간 이벤트 기획",
    field: "홍보",
    tasks: ["홍보·이벤트 기획"],
    store: { id: "store-bunsik", name: "월계분식" },
    budget: 30000,
    draftDue: day(-48),
    finalDue: day(-44),
    revisionLimit: 1,
    revisionCount: 0,
    plan: "시험 기간 2주 동안 학생 손님을 늘릴 이벤트를 기획하고 매장 포스터를 만들어 드릴게요.",
    planSentOn: day(-55),
    status: "completed",
    requestArrivedOn: day(-52),
    startedOn: day(-51),
    completedOn: day(-44),
    completedBy: "owner",
    files: [{ name: "이벤트_기획안.pdf", size: "2.6MB" }],
    myMessage: "기획안과 매장 포스터 파일이에요.",
    resultSummary: "기획안 · 포스터 1장",
    review: {
      rating: 5,
      points: ["결과물이 좋아요", "마감을 잘 지켜요"],
      text: "학생 손님이 확실히 늘었어요. 포스터도 예뻐요.",
      date: day(-44),
    },
    history: [
      { date: day(-55), text: "제안 보냄" },
      { date: day(-52), text: "제안 수락 · 의뢰서 도착" },
      { date: day(-51), text: "조건 동의 · 작업 시작" },
      { date: day(-48), text: "초안 제출 (기획안 · 포스터)" },
      { date: day(-44), text: "사장님이 완료 확인" },
    ],
  },
  {
    id: "work-206",
    kind: "request",
    title: "현수막 시안",
    field: "디자인",
    tasks: ["간판·현수막 시안"],
    store: { id: "store-happyhair", name: "해피헤어" },
    budget: 80000,
    draftDue: day(-48),
    finalDue: day(-44),
    revisionLimit: 1,
    revisionCount: 0,
    plan: "가게 앞 현수막 시안 2가지를 만들어 드릴게요.",
    planSentOn: day(-60),
    status: "canceled",
    startedOn: day(-58),
    files: [],
    history: [
      { date: day(-58), text: "의뢰 선정 · 작업 시작" },
      { date: day(-52), text: "사장님 사정으로 취소 · 착수 보상 16,000원 정산" },
    ],
    cancel: {
      canceledOn: day(-52),
      stage: "inProgress",
      reason: "작업이 필요없어졌어요.",
      message: "가게 사정으로 현수막 교체를 미루게 됐어요. 죄송해요.",
      reward: 16000,
    },
  },
];

/* 채팅방. work-103 은 사장님 예시의 같은 채팅방을 학생 쪽에서 본 것이다 */
export const SAMPLE_CHAT_THREADS: StudentChatThread[] = [
  {
    workId: "work-103",
    unreadCount: 0,
    messages: [
      { id: "m1", type: "system", text: "안전결제가 끝나 작업이 시작됐어요", at: dayAt(-2, 13, 50) },
      {
        id: "m2",
        type: "text",
        from: "me",
        text: "메뉴 사진 원본 파일 보내주실 수 있나요? 인쇄용이라 화질 좋은 게 필요해요.",
        at: yesterdayAt(14, 2),
      },
      { id: "m3", type: "text", from: "partner", text: "네, 지금 보내드릴게요.", at: yesterdayAt(14, 5) },
      {
        id: "m4",
        type: "file",
        from: "partner",
        name: "메뉴사진_원본.zip",
        detail: "사진 3장 · 12.8MB",
        at: yesterdayAt(14, 5),
      },
      {
        id: "m5",
        type: "text",
        from: "me",
        text: "감사합니다! 초록 계열로 시안 2개 만들어서 초안 마감일까지 보내드릴게요.",
        at: yesterdayAt(14, 22),
      },
    ],
  },
  {
    workId: "work-211",
    unreadCount: 2,
    messages: [
      { id: "m1", type: "system", text: "안전결제가 끝나 작업이 시작됐어요", at: dayAt(-9, 10, 0) },
      { id: "m2", type: "system", text: "초안을 보냈어요", at: dayAt(-4, 20, 10) },
      { id: "m3", type: "system", text: "수정 요청이 도착했어요", at: yesterdayAt(18, 40) },
      {
        id: "m4",
        type: "text",
        from: "partner",
        text: "2번 사진만 조금 밝게 해 주세요. 나머지는 좋아요!",
        at: yesterdayAt(18, 41),
      },
      {
        id: "m5",
        type: "text",
        from: "partner",
        text: "4번에는 시험 기간 이벤트 문구도 넣어 주세요.",
        at: yesterdayAt(18, 42),
      },
    ],
  },
  {
    workId: "work-212",
    unreadCount: 0,
    messages: [
      { id: "m1", type: "system", text: "조건에 동의해 작업이 시작됐어요", at: dayAt(-6, 11, 0) },
      {
        id: "m2",
        type: "text",
        from: "partner",
        text: "영업시간은 일요일 휴무로 고쳐 주세요. 사진은 좋아요!",
        at: dayAt(-5, 16, 20),
      },
      { id: "m3", type: "text", from: "me", text: "네, 반영해서 보내 드릴게요.", at: dayAt(-5, 16, 31) },
      { id: "m4", type: "system", text: "초안을 보냈어요", at: dayAt(-1, 21, 0) },
    ],
  },
  {
    workId: "work-201",
    unreadCount: 0,
    messages: [
      { id: "m1", type: "system", text: "작업이 완료됐어요", at: dayAt(-21, 15, 0) },
      {
        id: "m2",
        type: "text",
        from: "partner",
        text: "덕분에 로고 잘 쓰고 있어요. 고마워요 :)",
        at: dayAt(-21, 15, 12),
      },
    ],
  },
];

/* 조건에 동의하면 열리는 채팅방 (첫 메시지는 동의한 때 붙는다) */
SAMPLE_CHAT_THREADS.push({ workId: "work-213", unreadCount: 0, messages: [] });

/* 알림 시각과 맞추려고 내보낸다 */
export const LAST_REVISION_AT = yesterdayAt(18, 40);
export const ACCEPTED_AT = minutesAgo(120);
