CREATE TABLE specialty_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT specialty_categories_name_key UNIQUE (name)
);

ALTER TABLE specialties
    DROP CONSTRAINT specialties_name_key,
    ADD COLUMN specialty_category_id BIGINT NOT NULL,
    ADD CONSTRAINT specialties_specialty_category_id_name_key UNIQUE (specialty_category_id, name);
