CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_profile_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    budget BIGINT NOT NULL,
    deadline DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    selected_student_profile_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE job_specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    specialty_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT job_specialties_job_id_specialty_id_key UNIQUE (job_id, specialty_id)
);

CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    content TEXT,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT job_applications_job_id_student_profile_id_key UNIQUE (job_id, student_profile_id)
);
