CREATE TABLE job_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    submission_type VARCHAR(30) NOT NULL,
    revision_number INTEGER NOT NULL,
    file_urls JSONB NOT NULL,
    message TEXT NOT NULL,
    review_status VARCHAR(30) NOT NULL,
    review_comment TEXT,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT job_submissions_job_id_revision_number_key UNIQUE (job_id, revision_number),
    CONSTRAINT job_submissions_revision_number_type_check CHECK (
        (submission_type = 'DRAFT' AND revision_number = 0)
        OR (submission_type = 'REVISION' AND revision_number > 0)
    ),
    CONSTRAINT job_submissions_file_urls_check CHECK (
        jsonb_typeof(file_urls) = 'array' AND jsonb_array_length(file_urls) > 0
    )
);

CREATE UNIQUE INDEX job_submissions_one_pending_per_job_key
    ON job_submissions (job_id)
    WHERE review_status = 'PENDING';
