CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    job_application_id BIGINT NOT NULL,
    owner_user_id VARCHAR(26) NOT NULL,
    order_id VARCHAR(36) NOT NULL,
    amount BIGINT NOT NULL,
    refund_policy_agreed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    payment_key TEXT,
    approved_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT payments_order_id_key UNIQUE (order_id),
    CONSTRAINT payments_amount_positive_check CHECK (amount > 0)
);

CREATE UNIQUE INDEX payments_one_pending_per_job_key
    ON payments (job_id) WHERE status = 'PENDING';

CREATE UNIQUE INDEX payments_one_paid_per_job_key
    ON payments (job_id) WHERE status = 'PAID';
