ALTER TABLE chat_rooms
    ADD COLUMN owner_last_read_message_id BIGINT,
    ADD COLUMN student_last_read_message_id BIGINT;

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id VARCHAR(26) NOT NULL,
    sender_user_id VARCHAR(26) NOT NULL,
    type VARCHAR(10) NOT NULL,
    content TEXT,
    attachment_key TEXT,
    attachment_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_messages_type_check CHECK (type IN ('TEXT', 'IMAGE', 'FILE'))
);

CREATE INDEX chat_messages_room_id_id_idx ON chat_messages (room_id, id DESC);
CREATE INDEX chat_messages_room_sender_id_idx ON chat_messages (room_id, sender_user_id, id);
