CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    owner_profile_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    positive_points JSONB NOT NULL,
    content TEXT NOT NULL,
    rating INTEGER NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT reviews_job_id_key UNIQUE (job_id),
    CONSTRAINT reviews_rating_check CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT reviews_positive_points_check CHECK (jsonb_typeof(positive_points) = 'array')
);
