CREATE TABLE student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    university VARCHAR(255) NOT NULL,
    student_number VARCHAR(255) NOT NULL,
    major VARCHAR(255) NOT NULL,
    activity_area VARCHAR(255) NOT NULL,
    portfolio VARCHAR(255) NOT NULL,
    introduction TEXT,
    profile_image_url VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT student_profiles_user_id_key UNIQUE (user_id)
);
