CREATE TABLE proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    owner_profile_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    customer_problem VARCHAR(500) NOT NULL,
    proposed_solution VARCHAR(500) NOT NULL,
    work_plan VARCHAR(500) NOT NULL,
    proposed_fee BIGINT NOT NULL,
    draft_days INTEGER NOT NULL,
    final_days INTEGER NOT NULL,
    reference_image_urls JSONB NOT NULL,
    like_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    CONSTRAINT proposals_like_count_check CHECK (like_count >= 0),
    CONSTRAINT proposals_proposed_fee_check CHECK (proposed_fee > 0),
    CONSTRAINT proposals_days_check CHECK (draft_days >= 0 AND final_days >= draft_days),
    CONSTRAINT proposals_reference_image_urls_check CHECK (jsonb_typeof(reference_image_urls) = 'array')
);

CREATE INDEX proposals_owner_profile_id_idx ON proposals (owner_profile_id);
CREATE INDEX proposals_student_profile_id_idx ON proposals (student_profile_id);

CREATE TABLE proposal_specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    specialty_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT proposal_specialties_proposal_id_specialty_id_key UNIQUE (proposal_id, specialty_id)
);

CREATE TABLE proposal_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT proposal_likes_proposal_id_student_profile_id_key UNIQUE (proposal_id, student_profile_id)
);

CREATE INDEX proposal_likes_student_profile_id_idx ON proposal_likes (student_profile_id);
