CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    recipient_user_id VARCHAR(26) NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(26) NOT NULL,
    read_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_event_id_recipient_user_id_key UNIQUE (event_id, recipient_user_id)
);

CREATE INDEX notifications_recipient_user_id_created_at_id_idx
    ON notifications (recipient_user_id, created_at DESC, id DESC);
