-- 사장님이 학생 제안에 참고하도록 올리는 가게 고민. 제안·의뢰와 연결하지 않는 참고 정보다.
-- 해결한 고민은 지우지 않고 resolved_at을 남기며, 가게마다 해결되지 않은 고민은 하나만 둔다.
-- 운영 DB에는 같은 구조의 표와 인덱스를 먼저 만들어 두었으므로, 이미 있으면 그대로 둔다.
CREATE TABLE IF NOT EXISTS store_concerns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_profile_id BIGINT NOT NULL,
    title VARCHAR(60) NOT NULL,
    description VARCHAR(500),
    specialty_category_id BIGINT,
    resolved_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS store_concerns_open_owner_key ON store_concerns (owner_profile_id) WHERE resolved_at IS NULL;
