CREATE TABLE owner_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    business_number VARCHAR(255) NOT NULL,
    opened_at DATE,
    representative_name VARCHAR(255),
    store_name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    description TEXT,
    profile_image_url VARCHAR(255),
    store_image_url JSONB,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT owner_profiles_user_id_key UNIQUE (user_id),
    CONSTRAINT owner_profiles_business_number_key UNIQUE (business_number)
);
