CREATE TABLE student_specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    specialty_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT student_specialties_student_profile_id_specialty_id_key UNIQUE (student_profile_id, specialty_id)
);
