CREATE TABLE student_certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    certificate_name VARCHAR(255) NOT NULL,
    acquired_year INTEGER NOT NULL,
    issuing_organization VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
