CREATE TABLE business_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT business_categories_name_key UNIQUE (name)
);

ALTER TABLE owner_profiles ADD COLUMN category_id BIGINT NOT NULL;
