import type { OwnerChatThread, OwnerProposal, OwnerRequest, OwnerWork } from "../types";
import { yesterdayAt } from "./sampleTime";

/*
 * 임시 예시 데이터 (피그마 「작업 확인 · 받은 제안 상세 · 지원자 목록 · 보낸 의뢰 상세 ·
 * 결과물 보기 · 채팅방 · 작업계획서 보기」 내용). 홈 예시와 같은 id 를 쓴다.
 */

export const SAMPLE_WORKS: OwnerWork[] = [
  {
    id: "work-101",
    kind: "request",
    title: "인스타 게시물 5개 제작",
    field: "홍보",
    student: { name: "박지은", department: "시각디자인학과" },
    budget: 50000,
    draftDue: "2026-09-22",
    finalDue: "2026-09-29",
    revisionLimit: 1,
    revisionCount: 0,
    plan: "신메뉴와 시험 기간 이벤트를 알리는 인스타 게시물 5장을 만들어 드릴게요.\n· 방법: 가게 사진을 밝게 보정하고, 게시물마다 한 줄 문구를 크게 넣어요.\n· 일정: 9월 22일까지 초안 5장, 수정 요청이 오면 9월 29일까지 최종본을 드려요.\n· 결과물: 게시물 이미지 5장과 올릴 때 쓸 문구",
    planSentOn: "2026-09-15",
    status: "submitted",
    submittedOn: "2026-09-22",
    autoCompleteOn: "2026-09-29",
    files: [
      { name: "인스타 게시물 5장.zip", size: "18.2MB" },
      { name: "게시물 문구.jpg", size: "1.1MB" },
    ],
    studentMessage:
      "신메뉴 3개와 시험 기간 이벤트를 넣어 5장 만들었어요. 사진 밝기나 문구 중 바꾸고 싶은 곳을 말씀해 주세요!",
    history: [],
  },
  {
    id: "work-103",
    kind: "request",
    title: "메뉴판 디자인 변경",
    field: "디자인",
    student: { name: "김광운" },
    budget: 60000,
    draftDue: "2026-09-29",
    finalDue: "2026-10-02",
    revisionLimit: 1,
    revisionCount: 0,
    plan: "초록색을 살린 메뉴판 시안 2가지를 만들고, 고르신 쪽으로 다듬어 인쇄용으로 드릴게요.\n· 방법: 보내 주신 메뉴 사진을 보정해서 넣고, 인기 메뉴 3개는 크게 보여 드려요.\n· 일정: 9월 29일까지 초안 2가지, 수정 요청이 오면 10월 2일까지 최종본을 드려요.",
    planSentOn: "2026-09-18",
    status: "inProgress",
    files: [],
    history: [],
  },
  {
    id: "work-090",
    kind: "request",
    title: "메뉴판 제작",
    field: "디자인",
    student: { name: "김광운" },
    budget: 50000,
    draftDue: "2026-09-08",
    finalDue: "2026-09-12",
    revisionLimit: 1,
    revisionCount: 1,
    plan: "지금 메뉴를 한눈에 보이게 정리한 A3 메뉴판을 만들어 드릴게요.",
    planSentOn: "2026-09-01",
    status: "completed",
    completedOn: "2026-09-12",
    completedBy: "owner",
    files: [
      { name: "메뉴판_최종.pdf", size: "8.4MB" },
      { name: "메뉴판_원본.ai", size: "32.0MB" },
    ],
    studentMessage: "가격을 고친 최종본이에요. 인쇄소에 PDF를 그대로 보내시면 돼요!",
    history: [
      { date: "2026-09-05", text: "안전결제 · 작업 시작" },
      { date: "2026-09-08", text: "초안 도착 (메뉴판 시안 2가지)" },
      { date: "2026-09-09", text: "수정 요청 · 가격, 글자 크기" },
      { date: "2026-09-12", text: "최종본 도착 · 사장님이 완료 확인" },
    ],
  },
  {
    id: "work-085",
    kind: "request",
    title: "인스타 계정 만들기",
    field: "홍보",
    student: { name: "정하은" },
    budget: 30000,
    draftDue: "2026-08-30",
    finalDue: "2026-09-03",
    revisionLimit: 1,
    revisionCount: 0,
    plan: "가게 인스타 계정을 만들고 첫 게시물 3개를 올려 드릴게요.",
    planSentOn: "2026-08-25",
    status: "completed",
    completedOn: "2026-09-03",
    completedBy: "auto",
    files: [{ name: "계정_운영_안내.pdf", size: "2.3MB" }],
    studentMessage: "비밀번호는 채팅으로 따로 보내 드렸어요. 첫 게시물 3개도 올려 두었어요!",
    history: [
      { date: "2026-08-27", text: "안전결제 · 작업 시작" },
      { date: "2026-08-27", text: "초안 도착 (계정 · 게시물 3개)" },
      { date: "2026-09-03", text: "7일 지나 자동 완료" },
    ],
  },
  {
    id: "work-080",
    kind: "proposal",
    title: "네이버 지도 사진 정리",
    field: "홍보",
    student: { name: "박누리" },
    budget: 25000,
    draftDue: "2026-08-22",
    finalDue: "2026-08-26",
    revisionLimit: 1,
    revisionCount: 0,
    plan: "네이버 지도에 오래된 사진을 내리고 새 사진 10장을 올려 드릴게요.",
    planSentOn: "2026-08-18",
    status: "completed",
    completedOn: "2026-08-26",
    completedBy: "owner",
    files: [{ name: "새_매장사진_10장.zip", size: "26.5MB" }],
    studentMessage: "낮과 저녁 사진을 섞어 올렸어요. 원본도 함께 드려요.",
    history: [
      { date: "2026-08-20", text: "안전결제 · 작업 시작" },
      { date: "2026-08-22", text: "초안 도착 (사진 10장)" },
      { date: "2026-08-26", text: "사장님이 완료 확인" },
    ],
  },
  {
    id: "work-070",
    kind: "request",
    title: "가게 로고 만들기",
    field: "디자인",
    student: { name: "이은서" },
    budget: 70000,
    draftDue: "2026-08-08",
    finalDue: "2026-08-14",
    revisionLimit: 1,
    revisionCount: 1,
    plan: "닭 캐릭터를 넣은 로고 시안 3가지를 만들고, 고르신 쪽을 간판용으로 다듬어 드릴게요.",
    planSentOn: "2026-08-01",
    status: "completed",
    completedOn: "2026-08-14",
    completedBy: "owner",
    files: [
      { name: "치킨플러스_로고_최종.png", size: "24.1MB" },
      { name: "치킨플러스_로고_원본.ai", size: "48.6MB" },
    ],
    studentMessage:
      "말씀하신 대로 닭 캐릭터를 더 단순하게 다듬었어요. 간판에 쓸 원본 파일도 함께 드려요!",
    history: [
      { date: "2026-08-05", text: "안전결제 · 작업 시작" },
      { date: "2026-08-08", text: "초안 도착 (로고 시안 3가지)" },
      { date: "2026-08-09", text: "수정 요청 · 캐릭터 단순하게" },
      { date: "2026-08-14", text: "최종본 도착 · 사장님이 완료 확인" },
    ],
  },
];

export const SAMPLE_PROPOSALS: OwnerProposal[] = [
  {
    id: "prop-201",
    title: "카카오 맵 수정",
    field: "홍보",
    receivedOn: "2026-09-22",
    empathyCount: 27,
    student: {
      id: "student-nuri",
      name: "박누리",
      department: "미디어커뮤니케이션학부",
      year: "21학번",
      rating: 4.8,
      completedCount: 3,
    },
    problem:
      "가게 메뉴판이나 가격이 카카오 맵에서 뜨는 거랑 달라요. 지도를 보고 온 손님이 가격이 다르다고 당황하는 걸 봤어요.",
    solution:
      "카카오 맵의 메뉴·가격·영업시간을 지금 메뉴판과 똑같이 고치고, 대표 사진 3장을 새로 찍어 올려 드릴게요.",
    plan: "카카오 맵 정보를 지금 메뉴판과 똑같이 맞추고, 대표 사진을 새로 올려 드릴게요.\n· 방법: 메뉴판을 사진으로 찍어 메뉴 이름·가격·영업시간을 하나씩 대조하고, 틀린 곳을 카카오 맵 사장님 페이지에서 고쳐요.\n· 사진: 손님이 많이 찾는 메뉴 3개를 밝게 찍어 대표 사진으로 올려요.\n· 일정: 수락 후 1일 안에 초안(고칠 목록과 사진)을 보내 드리고, 확인해 주시면 2일 안에 반영해요.\n· 결과물: 고친 카카오 맵 화면 캡처와 원본 사진 파일",
    wishBudget: 30000,
    expectedDays: 3,
    attachments: ["카카오맵_캡처.png", "IMG_4821.jpg"],
  },
];

export const SAMPLE_REQUESTS: OwnerRequest[] = [
  {
    id: "req-102",
    title: "영어·중국어 메뉴판 번역",
    field: "글쓰기·번역",
    budget: 50000,
    draftDue: "2026-09-27",
    finalDue: "2026-09-30",
    revisionLimit: 1,
    tasks: ["영어 번역", "중국어 번역"],
    description:
      "메뉴 32개를 영어와 중국어로 번역해 주세요. 외국인 손님이 늘어서 메뉴판만 보고 바로 고를 수 있으면 좋겠어요.",
    attachments: ["지금_메뉴판.jpg"],
    applicants: [
      {
        student: {
          id: "student-haeun",
          name: "정하은",
          department: "영어영문학과",
          year: "22학번",
          rating: 4.9,
          completedCount: 4,
        },
        badges: ["영어 번역", "소개·공지 글쓰기"],
        plan: "메뉴 32개를 영어·중국어로 번역하고, 유학생 친구에게 자연스러운지 검수까지 받을게요.\n· 번역 방법: 메뉴 이름은 소리 나는 대로 적고(예: Tteokbokki), 아래에 재료와 맛을 한 줄로 설명해요. 맵기는 고추 개수로 표시할게요.\n· 검수: 영어는 원어민 교환학생에게, 중국어는 중국인 유학생에게 한 번 더 확인받아요.\n· 일정: 9월 23일까지 초안(한글·영어·중국어 대조표)을 보내 드리고, 수정 요청이 오면 9월 29일까지 최종본을 드려요.\n· 결과물: 인쇄용 PDF와 바로 고칠 수 있는 한글(HWP) 파일로 드려요.",
      },
      {
        student: {
          id: "student-lili",
          name: "왕리리",
          department: "동북아문화산업학부",
          year: "23학번",
          rating: 5.0,
          completedCount: 2,
        },
        badges: ["중국어 번역", "영어 번역"],
        plan: "중국어가 모국어라 중국 손님이 바로 알아듣는 표현으로 옮기고, 맵기 표시도 함께 정리할게요.\n· 번역 방법: 한국 음식 이름은 중국에서 실제로 쓰는 이름으로 바꾸고(예: 떡볶이 → 炒年糕), 영어에는 짧은 설명을 붙여요.\n· 추가: 땅콩·새우 같은 알레르기 재료를 아이콘으로 표시해 드려요.\n· 일정: 9월 22일까지 초안, 수정 요청이 오면 9월 28일까지 최종본을 드려요.\n· 결과물: 메뉴판 파일에 바로 붙일 수 있는 번역 표(엑셀)와 PDF",
      },
      {
        student: {
          id: "student-doyun",
          name: "김도윤",
          department: "국제학부",
          year: "21학번",
          completedCount: 0,
        },
        badges: ["영어 번역", "일본어 번역"],
        plan: "메뉴 이름은 소리 나는 대로 적고, 아래에 재료를 짧게 설명하는 방식으로 번역할게요.\n· 번역 방법: 영어를 먼저 번역하고, 중국어는 중국어 수업 교수님께 조언을 받아 다듬을게요.\n· 일정: 9월 24일까지 초안, 수정 요청이 오면 9월 30일까지 최종본을 드려요.\n· 결과물: 메뉴별 번역 표(구글 시트)와 인쇄용 PDF\n· 첫 작업이라 중간중간 진행 상황을 자주 공유해 드릴게요.",
      },
      {
        student: {
          id: "student-seoyun",
          name: "최서윤",
          department: "영어산업학과",
          year: "24학번",
          rating: 4.7,
          completedCount: 1,
        },
        badges: ["영어 번역", "메뉴판·가격표 디자인"],
        plan: "번역한 메뉴를 지금 메뉴판 모양 그대로 다시 넣어서, 바로 인쇄할 수 있게 만들어 드릴게요.\n· 번역 방법: 영어는 외국 손님이 읽기 쉬운 짧은 표현으로 옮기고, 중국어는 중국인 유학생 친구에게 확인받아요.\n· 추가: 인기 메뉴 3개에는 「추천」 표시를 달아 드려요.\n· 일정: 9월 25일까지 초안, 수정 요청이 오면 9월 30일까지 최종본을 드려요.\n· 결과물: 인쇄용 PDF와 고칠 수 있는 원본 파일",
      },
      {
        student: {
          id: "student-jiwoo",
          name: "한지우",
          department: "국제통상학부",
          year: "23학번",
          completedCount: 0,
        },
        badges: ["중국어 번역", "영어 번역"],
        plan: "중국 교환학생 때 익힌 표현으로 중국 손님이 바로 알아보는 메뉴 이름을 붙여 드릴게요.\n· 번역 방법: 중국어를 먼저 옮기고, 영어는 메뉴마다 재료를 한 줄로 설명해요.\n· 일정: 9월 26일까지 초안, 수정 요청이 오면 9월 30일까지 최종본을 드려요.\n· 결과물: 메뉴별 번역 표(엑셀)와 인쇄용 PDF\n· 첫 작업이라 초안 전에 번역 몇 개를 먼저 보여 드리고 방향을 맞출게요.",
      },
    ],
  },
  {
    id: "req-104",
    title: "봄 신메뉴 전단지",
    field: "디자인",
    budget: 40000,
    draftDue: "2026-10-03",
    finalDue: "2026-10-07",
    revisionLimit: 1,
    tasks: ["전단지·포스터 디자인"],
    description:
      "봄 신메뉴 3가지(허니갈릭, 치즈볼, 양념 반반)를 알리는 A4 전단지를 만들고 싶어요. 광운대 앞에서 나눠 줄 거라 학생들이 좋아할 느낌이면 좋겠어요.",
    attachments: ["신메뉴_사진.jpg", "지난_전단지.jpg"],
    applicants: [],
  },
];

export const SAMPLE_CHAT_THREADS: OwnerChatThread[] = [
  {
    workId: "work-103",
    messages: [
      { id: "m1", type: "system", text: "안전결제가 끝나 작업이 시작됐어요", at: yesterdayAt(13, 50) },
      {
        id: "m2",
        type: "text",
        from: "partner",
        text: "메뉴 사진 원본 파일 보내주실 수 있나요? 인쇄용이라 화질 좋은 게 필요해요.",
        at: yesterdayAt(14, 2),
      },
      { id: "m3", type: "text", from: "me", text: "네, 지금 보내드릴게요.", at: yesterdayAt(14, 5) },
      {
        id: "m4",
        type: "file",
        from: "me",
        name: "메뉴사진_원본.zip",
        detail: "사진 3장 · 12.8MB",
        at: yesterdayAt(14, 5),
      },
      {
        id: "m5",
        type: "text",
        from: "partner",
        text: "감사합니다! 초록 계열로 시안 2개 만들어서 금요일 오전까지 보내드릴게요.",
        at: yesterdayAt(14, 22),
      },
    ],
  },
  {
    workId: "work-101",
    messages: [
      { id: "m1", type: "system", text: "초안이 도착했어요", at: yesterdayAt(10, 4) },
      {
        id: "m2",
        type: "text",
        from: "partner",
        text: "초안 5장 올렸어요. 확인 부탁드려요!",
        at: yesterdayAt(10, 5),
      },
    ],
  },
  {
    workId: "work-070",
    messages: [
      { id: "m1", type: "system", text: "작업이 완료됐어요", at: "2026-08-14T17:00:00+09:00" },
      {
        id: "m2",
        type: "text",
        from: "me",
        text: "로고 정말 마음에 들어요. 후기 남겼어요!",
        at: "2026-08-14T17:20:00+09:00",
      },
      {
        id: "m3",
        type: "text",
        from: "partner",
        text: "후기 남겨 주셔서 감사합니다 :)",
        at: "2026-08-14T17:30:00+09:00",
      },
    ],
  },
];
