import type { StudentProfile } from "../types";
import { day } from "../../../lib/sampleTime";

/*
 * 학생 프로필 임시 예시 데이터 (피그마 「지원자 학생 프로필 보기」).
 * 지원자 · 제안 · 작업에 나오는 학생 id 와 같다.
 */

export const SAMPLE_STUDENT_PROFILES: StudentProfile[] = [
  {
    id: "student-haeun",
    name: "정하은",
    department: "영어영문학과",
    year: "22학번",
    rating: 4.9,
    completedCount: 4,
    intro: "외국어 메뉴판 번역과 소개 글을 주로 해요",
    proposalCount: 6,
    noShowCount: 0,
    onTimeRate: 100,
    badges: ["영어 번역", "중국어 번역", "소개·공지 글쓰기"],
    certificates: [
      { name: "TOEIC 950점", acquiredOn: "2025-03" },
      { name: "HSK 5급", acquiredOn: "2024-11" },
    ],
    portfolioUrl: "notion.so/haeun-portfolio",
    reviews: [
      {
        storeName: "월계분식",
        workTitle: "메뉴판 영어 번역",
        rating: 5.0,
        text: "외국인 손님이 메뉴를 바로 알아보고 주문해요. 궁금한 점도 쉽게 설명해 줬어요.",
        date: "2026-09-11",
      },
      {
        storeName: "광운카페",
        workTitle: "가게 소개 글",
        rating: 5.0,
        text: "약속한 날보다 하루 먼저 보내 줬고, 고칠 부분도 바로 반영해 줬어요.",
        date: "2026-08-27",
      },
      {
        storeName: "골목카페",
        workTitle: "인스타 공지 글",
        rating: 4.7,
        text: "사진 설명을 짧고 재밌게 써 줘서 손님 반응이 좋았어요.",
        date: "2026-08-04",
      },
    ],
  },
  {
    id: "student-lili",
    name: "왕리리",
    department: "동북아문화산업학부",
    year: "23학번",
    rating: 5.0,
    completedCount: 2,
    intro: "중국어가 모국어예요. 중국 손님 눈높이로 옮겨 드려요",
    proposalCount: 3,
    noShowCount: 0,
    onTimeRate: 100,
    badges: ["중국어 번역", "영어 번역"],
    certificates: [{ name: "TOPIK 6급", acquiredOn: "2024-05" }],
    reviews: [
      {
        storeName: "석계반점",
        workTitle: "가게 소개 중국어 번역",
        rating: 5.0,
        text: "중국 손님들이 메뉴를 보고 바로 주문해요.",
        date: "2026-09-05",
      },
      {
        storeName: "월계커피",
        workTitle: "메뉴판 중국어 번역",
        rating: 5.0,
        text: "왜 이렇게 옮겼는지까지 설명해 줘서 믿음이 갔어요.",
        date: "2026-08-20",
      },
    ],
  },
  {
    id: "student-doyun",
    name: "김도윤",
    department: "국제학부",
    year: "21학번",
    completedCount: 0,
    intro: "영어·일본어 번역을 공부하고 있어요",
    proposalCount: 1,
    noShowCount: 0,
    badges: ["영어 번역", "일본어 번역"],
    certificates: [{ name: "JLPT N2", acquiredOn: "2025-07" }],
    reviews: [],
  },
  {
    id: "student-seoyun",
    name: "최서윤",
    department: "영어산업학과",
    year: "24학번",
    rating: 4.7,
    completedCount: 1,
    intro: "번역한 메뉴를 메뉴판 디자인까지 맞춰 드려요",
    proposalCount: 2,
    noShowCount: 0,
    onTimeRate: 100,
    badges: ["영어 번역", "메뉴판·가격표 디자인"],
    certificates: [{ name: "TOEIC 900점", acquiredOn: "2025-01" }],
    portfolioUrl: "behance.net/seoyun-choi",
    reviews: [
      {
        storeName: "광운분식",
        workTitle: "메뉴판 영어 번역",
        rating: 4.7,
        text: "번역과 디자인을 한 번에 맡길 수 있어 편했어요.",
        date: "2026-09-01",
      },
    ],
  },
  {
    id: "student-jiwoo",
    name: "한지우",
    department: "국제통상학부",
    year: "23학번",
    completedCount: 0,
    intro: "중국 교환학생 때 익힌 표현으로 번역해요",
    proposalCount: 0,
    noShowCount: 0,
    badges: ["중국어 번역", "영어 번역"],
    certificates: [{ name: "HSK 6급", acquiredOn: "2025-06" }],
    reviews: [],
  },
  {
    id: "student-minjun",
    name: "오민준",
    department: "소프트웨어학부",
    year: "22학번",
    rating: 4.8,
    completedCount: 3,
    intro: "작은 가게에 맞는 홈페이지와 예약 페이지를 만들어요",
    proposalCount: 4,
    noShowCount: 0,
    onTimeRate: 67,
    badges: ["가게 홈페이지", "메뉴판(QR,웹,모바일)", "온라인 예약·주문서"],
    certificates: [{ name: "정보처리기사", acquiredOn: "2025-06" }],
    portfolioUrl: "github.com/minjun-oh",
    reviews: [
      {
        storeName: "석계반점",
        workTitle: "온라인 예약서",
        rating: 5.0,
        text: "전화 예약이 확 줄었어요. 쓰는 법도 친절하게 알려 줬어요.",
        date: "2026-09-10",
      },
      {
        storeName: "월계떡집",
        workTitle: "가게 소개 홈페이지",
        rating: 4.6,
        text: "메뉴 사진이 잘 보이게 만들어 줬어요. 조금 늦었지만 꼼꼼했어요.",
        date: "2026-08-18",
      },
    ],
  },
  {
    id: "student-seoyeon",
    name: "박서연",
    department: "정보융합학부",
    year: "23학번",
    completedCount: 0,
    intro: "노션·구글 도구로 바로 고칠 수 있게 만들어요",
    proposalCount: 1,
    noShowCount: 0,
    badges: ["가게 홈페이지"],
    certificates: [],
    reviews: [],
  },
  {
    id: "student-nuri",
    name: "박누리",
    department: "미디어커뮤니케이션학부",
    year: "21학번",
    rating: 4.8,
    completedCount: 3,
    intro: "지도·SNS에 보이는 가게 모습을 정리해 드려요",
    proposalCount: 8,
    noShowCount: 0,
    onTimeRate: 100,
    badges: ["음식·매장 사진", "SNS 게시물", "리뷰 분석"],
    certificates: [],
    portfolioUrl: "instagram.com/nuri.shot",
    reviews: [
      {
        storeName: "치킨플러스",
        workTitle: "네이버 지도 사진 정리",
        rating: 5.0,
        text: "낮과 저녁 사진을 섞어 올려 줘서 가게 분위기가 잘 보여요.",
        date: day(-27),
      },
      {
        storeName: "광운카페",
        workTitle: "인스타 메뉴 사진",
        rating: 4.6,
        text: "메뉴 사진을 정말 맛있어 보이게 찍어 줬어요.",
        date: "2026-07-30",
      },
      {
        storeName: "월계분식",
        workTitle: "리뷰 정리",
        rating: 4.8,
        text: "손님들이 아쉬워한 점을 표로 정리해 줘서 바로 고쳤어요.",
        date: "2026-07-12",
      },
    ],
  },
  {
    id: "student-jieun",
    name: "박지은",
    department: "국제통상학부",
    year: "25학번",
    rating: 4.8,
    completedCount: 1,
    intro: "인스타 게시물과 짧은 영상을 만들어요",
    proposalCount: 2,
    noShowCount: 0,
    onTimeRate: 100,
    badges: ["SNS 게시물", "영상 제작 및 편집"],
    certificates: [],
    reviews: [
      {
        storeName: "광운카페",
        workTitle: "신메뉴 SNS 게시물",
        rating: 4.8,
        text: "게시물마다 문구가 짧고 눈에 띄었어요.",
        date: "2026-08-30",
      },
    ],
  },
  {
    id: "student-kwangwoon",
    name: "김광운",
    department: "경영학부",
    year: "24학번",
    rating: 4.7,
    completedCount: 6,
    intro: "메뉴판·로고 디자인을 주로 해요",
    proposalCount: 6,
    noShowCount: 0,
    onTimeRate: 100,
    badges: ["메뉴판·가격표 디자인", "로고 디자인", "SNS 게시물"],
    certificates: [
      { name: "GTQ 1급", acquiredOn: "2023-08" },
      { name: "ACP (Adobe 인증)", acquiredOn: "2024-02" },
    ],
    portfolioUrl: "behance.net/kwangwoon",
    reviews: [
      {
        storeName: "공룡카페",
        workTitle: "가게 로고 디자인",
        rating: 5.0,
        text: "귀여운 공룡 캐릭터가 가게랑 잘 어울려요. 스티커로도 만들어 쓰고 있어요!",
        date: day(-21),
      },
      {
        storeName: "월계분식",
        workTitle: "배달앱 메뉴 설명 글",
        rating: 4.0,
        text: "메뉴마다 맛이 잘 느껴지게 써 줬어요. 배달 주문이 늘었어요.",
        date: day(-36),
      },
      {
        storeName: "월계분식",
        workTitle: "시험 기간 이벤트 기획",
        rating: 5.0,
        text: "학생 손님이 확실히 늘었어요. 포스터도 예뻐요.",
        date: day(-44),
      },
    ],
  },
  {
    id: "student-eunseo",
    name: "이은서",
    department: "시각디자인학과",
    year: "23학번",
    rating: 4.9,
    completedCount: 6,
    intro: "메뉴판·간판처럼 가게 얼굴이 되는 디자인을 해요",
    proposalCount: 9,
    noShowCount: 0,
    onTimeRate: 100,
    badges: ["메뉴판·가격표 디자인", "간판·현수막 시안", "로고 디자인"],
    certificates: [{ name: "GTQ 1급", acquiredOn: "2024-08" }],
    portfolioUrl: "behance.net/eunseo-lee",
    reviews: [
      {
        storeName: "치킨플러스",
        workTitle: "가게 로고 만들기",
        rating: 5.0,
        text: "닭 캐릭터를 단순하게 다듬어 줘서 간판에도 잘 어울려요.",
        date: day(-39),
      },
      {
        storeName: "월계분식",
        workTitle: "메뉴판 시안",
        rating: 5.0,
        text: "인기 메뉴가 눈에 확 들어와서 주문이 빨라졌어요.",
        date: "2026-09-20",
      },
      {
        storeName: "석계반점",
        workTitle: "간판 시안",
        rating: 4.8,
        text: "시안 두 가지가 모두 깔끔해서 고르기 어려웠어요.",
        date: "2026-07-18",
      },
    ],
  },
];
